### ISSUE TITLE
Issue with colors

### ISSUE THREAD

**Issue by seawatts** [chrishunt/color-schemes#6]
I tried installing your themes in vim and iTerm2. They both seem to be installed however they look different when I go into tmux. And I cant see the line number anymore. Any ideas?

**Comment by chrishunt** [comment]
Hi @seawatts! Do you know if you have 256 colors enabled in tmux? Do you have [this setting](https://github.com/chrishunt/dot-files/blob/34aec6127c40dfb227f0c01c5e1e23fdebc03a2b/.tmux.conf#L5-L6) in your `tmux.conf`?

```
# use 256 term for pretty colors
set -g default-terminal "screen-256color"
```

You should see this set in the environment as well:

``` bash
$ echo $TERM
screen-256color
```

**Comment by seawatts** [comment]
Yeah that was kinda the issue. I actually found out there is a setting you can change in iTerm2 to set the "Report Terminal Type" to "xterm-256color"
